export type SupportedLanguage = 'en' | 'fr' | 'ar';

export type LocalizedStringList = Record<SupportedLanguage, string[]>;

export interface ZodiacHealthData {
	element: 'Fire' | 'Earth' | 'Air' | 'Water';
	planet: 'Mars' | 'Venus' | 'Mercury' | 'Moon' | 'Sun' | 'Jupiter' | 'Saturn';
	watchOutFor: LocalizedStringList;
	avoid: LocalizedStringList;
	foods: LocalizedStringList;
	spiritualProtection: LocalizedStringList;
	westAfricanTraditions?: LocalizedStringList;
}

// Keyed by Burj remainder: 1..12
export const ZODIAC_HEALTH_DATA_BY_BURUJ: Record<number, ZodiacHealthData> = {
	1: {
		element: 'Fire',
		planet: 'Mars',
		watchOutFor: {
			en: [
				'Headaches and head pain',
				'High body heat and fevers',
				'Getting angry too quickly',
				'Burns and minor accidents',
				'Feeling restless and stressed',
			],
			fr: [
				'Maux de tête et douleurs à la tête',
				'Chaleur corporelle élevée et fièvres',
				'Colère qui monte trop vite',
				'Brûlures et petits accidents',
				'Agitation et stress',
			],
			ar: [
				'صداع وآلام في الرأس',
				'ارتفاع حرارة الجسم والحمّى',
				'سرعة الغضب والانفعال',
				'حروق وحوادث بسيطة',
				'توتّر وقلق وحركة زائدة',
			],
		},
		avoid: {
			en: [
				'Too much spicy or hot food',
				'Getting into arguments (drains your energy)',
				'Working without rest',
				'Being in direct sun during hottest hours',
				'Making big decisions when angry',
			],
			fr: [
				'Trop d’aliments épicés ou très chauds',
				'Les disputes (ça vide ton énergie)',
				'Travailler sans repos',
				'Le soleil direct aux heures les plus chaudes',
				'Prendre de grandes décisions en colère',
			],
			ar: [
				'الإفراط في الأطعمة الحارة أو كثيرة التوابل',
				'الدخول في جدال (يستنزف طاقتك)',
				'العمل دون راحة',
				'التعرّض للشمس مباشرة في أشدّ الحر',
				'اتخاذ قرارات كبيرة وأنت غاضب',
			],
		},
		foods: {
			en: [
				'Cucumber and watermelon (cooling)',
				'Fresh mint tea',
				'Light soups and broths',
				'Dates (for energy balance)',
				'Plenty of clean water',
			],
			fr: [
				'Concombre et pastèque (rafraîchissants)',
				'Thé à la menthe fraîche',
				'Soupes légères et bouillons',
				'Dattes (équilibre énergétique)',
				'Beaucoup d’eau propre',
			],
			ar: [
				'خيار وبطيخ (مُبرِّدان)',
				'شاي نعناع طازج',
				'شوربات خفيفة ومرق',
				'تمر (لتوازن الطاقة)',
				'ماء نظيف بكثرة',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Salām' (O Peace) when feeling angry",
				'Make wudu with cool water when stressed',
				'Wear Red Carnelian for protection',
				'Burn Frankincense on Tuesdays',
				'Practice patience through deep breathing',
			],
			fr: [
				"Récite « Yā Salām » (Ô Paix) quand tu sens la colère",
				"Fais les ablutions (wuḍūʾ) avec de l’eau fraîche en cas de stress",
				'Porte une cornaline rouge (protection)',
				'Brûle de l’encens (oliban) le mardi',
				'Cultive la patience par une respiration lente',
			],
			ar: [
				'ردّد «يا سلام» عند شعور الغضب',
				'توضّأ بماء بارد عند التوتر',
				'ارتدِ عقيقًا أحمر (كارنيليان) للحفظ',
				'بخِّر باللبان يوم الثلاثاء',
				'درّب نفسك على الصبر بالتنفّس العميق',
			],
		},
	},
	2: {
		element: 'Earth',
		planet: 'Venus',
		watchOutFor: {
			en: [
				'Throat and neck problems',
				'Weight gain from comfort eating',
				'Feeling stuck or unmotivated',
				'Shoulder and neck tension',
				'Digestive slowness',
			],
			fr: [
				'Problèmes de gorge et de cou',
				'Prise de poids par “manger réconfort”',
				'Sensation de blocage ou manque de motivation',
				'Tension dans les épaules et le cou',
				'Digestion lente',
			],
			ar: [
				'مشاكل الحلق والرقبة',
				'زيادة وزن بسبب الأكل العاطفي',
				'شعور بالجمود أو قلة الحماس',
				'شدّ في الكتفين والرقبة',
				'بطء في الهضم',
			],
		},
		avoid: {
			en: [
				'Eating too much sweet or rich food',
				'Sitting for too long without movement',
				'Being stubborn about health issues',
				'Wearing tight necklaces or collars during prayer',
				'Ignoring early signs of throat discomfort',
			],
			fr: [
				'Trop de sucre ou de nourriture riche',
				'Rester assis trop longtemps sans bouger',
				'Être têtu face aux signaux du corps',
				"Porter des colliers/cols serrés pendant la prière",
				'Ignorer les premiers signes d’inconfort à la gorge',
			],
			ar: [
				'الإفراط في الحلويات أو الأطعمة الدسمة',
				'الجلوس طويلاً دون حركة',
				'العناد مع إشارات الجسد',
				'لبس ما يضيّق الرقبة أثناء الصلاة',
				'تجاهل بدايات ألم/خشونة الحلق',
			],
		},
		foods: {
			en: [
				'Green vegetables (especially spinach)',
				'Honey in warm water (morning)',
				'Olive oil',
				'Fresh herbs (parsley, mint)',
				'Light meals in the evening',
			],
			fr: [
				'Légumes verts (surtout les épinards)',
				'Miel dans de l’eau tiède (le matin)',
				'Huile d’olive',
				'Herbes fraîches (persil, menthe)',
				'Repas légers le soir',
			],
			ar: [
				'خضروات خضراء (خصوصًا السبانخ)',
				'عسل مع ماء دافئ صباحًا',
				'زيت الزيتون',
				'أعشاب طازجة (بقدونس، نعناع)',
				'وجبات خفيفة مساءً',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Ḥafīẓ' (O Preserver) for stability",
				'Wear Emerald or a green stone',
				'Burn Rose incense on Fridays',
				'Practice gratitude before eating',
				'Give sadaqah on Fridays for blessings',
			],
			fr: [
				"Récite « Yā Ḥafīẓ » (Ô Protecteur) pour la stabilité",
				'Porte une émeraude (ou une pierre verte)',
				'Brûle un encens de rose le vendredi',
				'Exprime la gratitude avant de manger',
				'Donne une sadaqa le vendredi (baraka)',
			],
			ar: [
				'ردّد «يا حفيظ» للثبات والحفظ',
				'ارتدِ زمردًا أو حجرًا أخضر',
				'بخِّر بالورد يوم الجمعة',
				'استحضر الشكر قبل الطعام',
				'تصدّق يوم الجمعة للبركة',
			],
		},
	},
	3: {
		element: 'Air',
		planet: 'Mercury',
		watchOutFor: {
			en: [
				'Breathing problems and chest tightness',
				'Anxiety and nervousness',
				'Hand and arm pain',
				'Trouble sleeping from overthinking',
				'Scattered energy',
			],
			fr: [
				'Difficultés respiratoires et oppression de la poitrine',
				'Anxiété et nervosité',
				'Douleurs des mains et des bras',
				'Insomnie à cause du mental',
				'Énergie dispersée',
			],
			ar: [
				'ضيق تنفّس وشدّ في الصدر',
				'قلق وتوتر عصبي',
				'ألم في اليدين والذراعين',
				'صعوبة نوم بسبب كثرة التفكير',
				'تشتّت الطاقة',
			],
		},
		avoid: {
			en: [
				'Talking too much (wastes your energy)',
				'Cold or damp air',
				'Doing too many things at once',
				'Smoking or breathing incense in closed rooms',
				'Staying up late scrolling on phone',
			],
			fr: [
				'Trop parler (ça gaspille ton énergie)',
				'Air froid ou humide',
				'Faire trop de choses à la fois',
				'Fumer ou respirer l’encens dans une pièce fermée',
				'Veiller tard à scroller sur le téléphone',
			],
			ar: [
				'كثرة الكلام (تُبدِّد طاقتك)',
				'هواء بارد أو رطب',
				'تعدّد المهام في وقت واحد',
				'التدخين أو استنشاق البخور في مكان مغلق',
				'السهر على الهاتف',
			],
		},
		foods: {
			en: [
				'Ginger tea (warm, not hot)',
				'Dates and honey',
				'Warm broths and soups',
				'Fennel seeds (for digestion)',
				'Foods that are easy to digest',
			],
			fr: [
				'Tisane de gingembre (tiède, pas brûlante)',
				'Dattes et miel',
				'Bouillons et soupes chaudes',
				'Graines de fenouil (digestion)',
				'Aliments faciles à digérer',
			],
			ar: [
				'شاي زنجبيل دافئ (ليس حارًا جدًا)',
				'تمر وعسل',
				'مرق وشوربات دافئة',
				'بذور الشمر للهضم',
				'أطعمة سهلة الهضم',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā ʿAlīm' (O All-Knowing) for calm",
				'Wear Yellow Agate',
				'Burn Mastic incense on Wednesdays',
				'Write down worries instead of speaking them all',
				'Practice breathing exercises before sleep',
			],
			fr: [
				"Récite « Yā ʿAlīm » (Ô Savant) pour l’apaisement",
				'Porte une agate jaune',
				'Brûle du mastic le mercredi',
				"Écris tes soucis au lieu de tout dire",
				'Fais des exercices respiratoires avant de dormir',
			],
			ar: [
				'ردّد «يا عليم» لسكينة القلب',
				'ارتدِ عقيقًا أصفر',
				'بخِّر بالمستكة يوم الأربعاء',
				'دوّن همومك بدل كثرة الكلام',
				'تمارين تنفّس قبل النوم',
			],
		},
	},
	4: {
		element: 'Water',
		planet: 'Moon',
		watchOutFor: {
			en: [
				'Stomach problems and bloating',
				'Emotional eating',
				'Chest and breast sensitivity',
				'Holding water in the body',
				'Mood affecting digestion',
			],
			fr: [
				'Problèmes d’estomac et ballonnements',
				'Manger sous l’émotion',
				'Sensibilité de la poitrine',
				'Rétention d’eau',
				'Humeur qui influence la digestion',
			],
			ar: [
				'مشاكل معدة وانتفاخ',
				'أكل عاطفي',
				'حساسية في الصدر',
				'احتباس سوائل',
				'المزاج يؤثر على الهضم',
			],
		},
		avoid: {
			en: [
				'Cold or raw foods when the moon is changing',
				'Eating when emotionally upset',
				'Dairy products when feeling sick',
				'For women: swimming during menstruation',
				'Holding onto emotional pain',
			],
			fr: [
				'Aliments froids ou crus quand la lune change',
				'Manger quand tu es bouleversé(e)',
				'Produits laitiers quand tu te sens malade',
				"Pour les femmes : nager pendant les menstrues",
				'Garder la douleur émotionnelle en soi',
			],
			ar: [
				'الأطعمة الباردة أو النيئة عند تغيّر القمر',
				'الأكل وأنت منزعج عاطفيًا',
				'الإكثار من الألبان عند المرض',
				'للنساء: السباحة أثناء الحيض',
				'كتمان الألم العاطفي',
			],
		},
		foods: {
			en: [
				'Warm soups (especially chicken soup)',
				'Ginger tea',
				'Fennel tea (for stomach)',
				'Foods cooked with love and intention',
				'Moderate portions',
			],
			fr: [
				'Soupes chaudes (surtout bouillon de poulet)',
				'Tisane de gingembre',
				'Tisane de fenouil (estomac)',
				"Nourriture cuisinée avec intention et douceur",
				'Portions modérées',
			],
			ar: [
				'شوربات دافئة (خصوصًا شوربة الدجاج)',
				'شاي زنجبيل',
				'شاي الشمر للمعدة',
				'طعام مطبوخ بنية طيبة',
				'كميات معتدلة',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Raḥmān' (O Most Merciful) for emotional healing",
				'Wear Pearl or Moonstone',
				'Burn Camphor on Mondays',
				'Make wudu when feeling emotional',
				'Protect yourself during full moon nights',
			],
			fr: [
				"Récite « Yā Raḥmān » (Ô Tout Miséricordieux) pour guérir le cœur",
				'Porte une perle ou une pierre de lune',
				'Brûle du camphre le lundi',
				"Fais le wuḍūʾ quand l’émotion monte",
				'Sois vigilant(e) les nuits de pleine lune',
			],
			ar: [
				'ردّد «يا رحمن» لشفاء القلب',
				'ارتدِ لؤلؤًا أو حجر القمر',
				'بخِّر بالكافور يوم الاثنين',
				'توضّأ عند غلبة العاطفة',
				'تحصّن في ليالي البدر',
			],
		},
	},
	5: {
		element: 'Fire',
		planet: 'Sun',
		watchOutFor: {
			en: [
				'Heart racing or palpitations',
				'Back and spine pain',
				'Eye strain or sensitivity',
				'Exhaustion from heat',
				'Pride causing stress',
			],
			fr: [
				'Palpitations ou cœur qui s’emballe',
				'Douleurs du dos et de la colonne',
				'Fatigue oculaire ou sensibilité',
				'Épuisement dû à la chaleur',
				'Fierté/ego qui crée du stress',
			],
			ar: [
				'خفقان أو تسارع نبض',
				'ألم في الظهر والعمود الفقري',
				'إجهاد أو حساسية في العينين',
				'إنهاك من الحر',
				'كبر/غرور يسبب توترًا',
			],
		},
		avoid: {
			en: [
				'Letting ego control you (hurts the heart)',
				'Overworking in hot weather',
				'Fasting without proper preparation',
				'Staring at sun or fire during rituals',
				'Ignoring chest discomfort',
			],
			fr: [
				"Laisser l’ego te diriger (ça fatigue le cœur)",
				'Trop travailler par forte chaleur',
				'Jeûner sans préparation adaptée',
				"Fixer le soleil ou le feu pendant des pratiques",
				'Ignorer un inconfort dans la poitrine',
			],
			ar: [
				'ترك النفس والغرور يقودانك (يتعب القلب)',
				'الإفراط في العمل وقت الحر',
				'الصيام دون تهيئة مناسبة',
				'التحديق في الشمس أو النار أثناء الممارسات',
				'تجاهل ألم/ضيق الصدر',
			],
		},
		foods: {
			en: [
				'Saffron tea (especially supportive for Leo)',
				'Dates and honey',
				'Foods that support the heart',
				'Golden-colored foods (turmeric, yellow lentils)',
				'Stay hydrated',
			],
			fr: [
				'Thé au safran (soutien, surtout pour le Lion)',
				'Dattes et miel',
				'Aliments qui soutiennent le cœur',
				'Aliments dorés (curcuma, lentilles jaunes)',
				'Bien t’hydrater',
			],
			ar: [
				'شاي الزعفران (مفيد خاصة للأسد)',
				'تمر وعسل',
				'أطعمة تدعم القلب',
				'أطعمة صفراء/ذهبية (كركم، عدس أصفر)',
				'حافظ على الترطيب',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Malik' (O King) with humility",
				'Wear Yellow Topaz or Gold',
				'Burn Frankincense and Saffron on Sundays',
				'Practice humility in prayer',
				'Give charity for heart protection',
			],
			fr: [
				"Récite « Yā Malik » (Ô Roi) avec humilité",
				'Porte une topaze jaune (ou de l’or)',
				'Brûle oliban et safran le dimanche',
				'Exerce l’humilité dans la prière',
				'Donne en aumône pour protéger le cœur',
			],
			ar: [
				'ردّد «يا ملك» بتواضع',
				'ارتدِ توبازًا أصفر أو ذهبًا',
				'بخِّر باللبان والزعفران يوم الأحد',
				'تدرّب على التواضع في الصلاة',
				'تصدّق لحفظ القلب',
			],
		},
	},
	6: {
		element: 'Earth',
		planet: 'Mercury',
		watchOutFor: {
			en: [
				'Stomach and intestine problems',
				'Allergies and skin reactions',
				'Anxiety about health',
				'Not eating properly from worry',
				'Overthinking making you sick',
			],
			fr: [
				'Problèmes d’estomac et d’intestins',
				'Allergies et réactions cutanées',
				'Anxiété liée à la santé',
				"Manger mal à cause des inquiétudes",
				'Le mental excessif qui épuise le corps',
			],
			ar: [
				'مشاكل المعدة والأمعاء',
				'حساسيات وتفاعلات جلدية',
				'قلق زائد بشأن الصحة',
				'سوء الأكل بسبب الهم',
				'كثرة التفكير تُتعب الجسد',
			],
		},
		avoid: {
			en: [
				'Being too obsessed with cleanliness (can weaken resilience)',
				'Skipping meals',
				'Worrying constantly about illness',
				'Drinking unclean water',
				'Criticizing yourself too harshly',
			],
			fr: [
				"Être obsédé(e) par la propreté (ça peut fragiliser)",
				'Sauter des repas',
				'S’inquiéter en permanence des maladies',
				'Boire une eau douteuse',
				'Te juger trop durement',
			],
			ar: [
				'الوسوسة المفرطة بالنظافة (تضعف المناعة النفسية)',
				'ترك الوجبات',
				'القلق الدائم من المرض',
				'شرب ماء غير نظيف',
				'قسوة النقد على النفس',
			],
		},
		foods: {
			en: [
				'Yogurt and probiotic foods',
				'Whole grains and fiber',
				'Olive oil (daily)',
				'Simple, clean foods',
				'Herbal teas (chamomile, mint)',
			],
			fr: [
				'Yaourt et aliments probiotiques',
				'Céréales complètes et fibres',
				'Huile d’olive (au quotidien)',
				'Aliments simples et “propres”',
				'Tisanes (camomille, menthe)',
			],
			ar: [
				'زبادي وأطعمة بروبيوتيك',
				'حبوب كاملة وألياف',
				'زيت الزيتون يوميًا',
				'أطعمة بسيطة ونظيفة',
				'شاي أعشاب (بابونج، نعناع)',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Ḥakīm' (O Most Wise) for peace",
				'Wear Yellow Jasper',
				'Burn Mastic on Wednesdays',
				"Renew tawakkul (trust in Allah's protection)",
				'Practice self-compassion',
			],
			fr: [
				"Récite « Yā Ḥakīm » (Ô Sage) pour la tranquillité",
				'Porte un jaspe jaune',
				'Brûle du mastic le mercredi',
				"Renouvelle le tawakkul (confiance en la protection d’Allah)",
				'Fais preuve de douceur envers toi-même',
			],
			ar: [
				'ردّد «يا حكيم» للسكينة',
				'ارتدِ يشبًا أصفر',
				'بخِّر بالمستكة يوم الأربعاء',
				'جدّد التوكّل على الله',
				'ارحم نفسك وكن رفيقًا بها',
			],
		},
	},
	7: {
		element: 'Air',
		planet: 'Venus',
		watchOutFor: {
			en: [
				'Kidney and bladder problems',
				'Lower back pain',
				'Skin issues (acne, rashes)',
				'Sugar imbalances',
				'Decision stress',
			],
			fr: [
				'Problèmes des reins et de la vessie',
				'Douleurs lombaires',
				'Problèmes de peau (acné, irritations)',
				'Déséquilibre du sucre',
				'Stress lié aux décisions',
			],
			ar: [
				'مشاكل الكلى والمثانة',
				'ألم أسفل الظهر',
				'مشاكل جلدية (حبوب، طفح)',
				'اختلالات السكر',
				'توتر بسبب الحيرة والقرار',
			],
		},
		avoid: {
			en: [
				'Not drinking enough water',
				'Too much salt in food',
				'Holding urine when you need to go',
				'Artificial sweeteners',
				'Being around toxic people (affects balance)',
			],
			fr: [
				'Ne pas boire assez d’eau',
				'Trop de sel',
				'Retenir l’urine',
				'Édulcorants artificiels',
				'Côtoyer des personnes toxiques (déséquilibre)',
			],
			ar: [
				'قلة شرب الماء',
				'الإفراط في الملح',
				'حبس البول عند الحاجة',
				'محليات صناعية',
				'مخالطة أشخاص سلبيين (تخلّ بالتوازن)',
			],
		},
		foods: {
			en: [
				'Plenty of clean water (most important!)',
				'Cucumber and watermelon',
				'Herbal teas',
				'Foods with natural sweetness',
				'Balanced meals (not too much of anything)',
			],
			fr: [
				'Beaucoup d’eau propre (le plus important !)',
				'Concombre et pastèque',
				'Tisanes',
				'Aliments naturellement sucrés',
				'Repas équilibrés (sans excès)',
			],
			ar: [
				'ماء نظيف بكثرة (الأهم!)',
				'خيار وبطيخ',
				'شاي أعشاب',
				'أطعمة بحلاوة طبيعية',
				'وجبات متوازنة بلا إفراط',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā ʿAdl' (O Just One) for balance",
				'Wear Opal or Lapis Lazuli',
				'Burn Rose incense on Fridays',
				'Seek balance in all things',
				'Make decisions with istikhārah',
			],
			fr: [
				"Récite « Yā ʿAdl » (Ô Juste) pour l’équilibre",
				'Porte une opale ou du lapis-lazuli',
				'Brûle un encens de rose le vendredi',
				'Cherche l’équilibre en toute chose',
				'Prends tes décisions avec l’istikhāra',
			],
			ar: [
				'ردّد «يا عدل» لطلب التوازن',
				'ارتدِ أوبالًا أو لازورد',
				'بخِّر بالورد يوم الجمعة',
				'اطلب التوازن في كل الأمور',
				'استخر الله قبل القرار',
			],
		},
	},
	8: {
		element: 'Water',
		planet: 'Mars',
		watchOutFor: {
			en: [
				'Private area problems and infections',
				'Bladder and urinary issues',
				'Emotional pain showing as body pain',
				'Blood problems',
				'Holding grudges making you sick',
			],
			fr: [
				'Problèmes intimes et infections',
				'Troubles urinaires et de la vessie',
				'Douleur émotionnelle qui se somatise',
				'Problèmes liés au sang',
				'Rancune qui rend malade',
			],
			ar: [
				'مشاكل خاصة/التهابات',
				'مشاكل بولية ومثانة',
				'ألم عاطفي يظهر كألم جسدي',
				'مشاكل في الدم',
				'حقد وكتمان يمرضك',
			],
		},
		avoid: {
			en: [
				'Holding grudges (creates poison inside you)',
				'Too much intimate activity (drains energy)',
				'Excessive spicy food',
				'Bathing during Mars hours on Tuesday',
				'Exposure to negative spiritual energy',
				'Being around stagnant or dirty water',
			],
			fr: [
				"Garder rancune (ça crée un “poison” intérieur)",
				"Trop d’activité intime (épuise l’énergie)",
				'Excès d’aliments épicés',
				"Se laver pendant les “heures de Mars” le mardi",
				'Exposition à des énergies spirituelles négatives',
				"Rester près d’eaux stagnantes ou sales",
			],
			ar: [
				'حمل الضغائن (يصنع سمًّا داخليًا)',
				'كثرة المعاشرة (تستنزف الطاقة)',
				'الإفراط في الأكل الحار',
				'الاغتسال في ساعات المريخ يوم الثلاثاء',
				'التعرّض لطاقة روحية سلبية',
				'القرب من ماء راكد أو متّسخ',
			],
		},
		foods: {
			en: [
				'Pomegranate (especially supportive for Scorpio)',
				"Black seed (Ḥabba Sawdā') daily",
				'Honey water in the morning',
				'Dates',
				'Foods used with Myrrh essence',
			],
			fr: [
				'Grenade (soutien, surtout pour le Scorpion)',
				"Nigelle (ḥabba sawdāʾ) au quotidien",
				"Eau + miel le matin",
				'Dattes',
				'Aliments associés à l’essence de myrrhe',
			],
			ar: [
				'رمان (مفيد خاصة للعقرب)',
				"حبة السوداء يوميًا",
				'ماء مع عسل صباحًا',
				'تمر',
				'أطعمة مع رائحة/جوهر المرّ',
			],
		},
		spiritualProtection: {
			en: [
				'Recite Ayat al-Kursi daily',
				'Wear Red Carnelian',
				'Burn Myrrh incense regularly',
				'Bathe with Sidr leaves weekly',
				'Practice forgiveness to release inner poison',
				'Regular ruqyah for spiritual protection',
			],
			fr: [
				'Récite Ayat al-Kursī chaque jour',
				'Porte une cornaline rouge',
				'Brûle de la myrrhe régulièrement',
				'Bain aux feuilles de sidr (hebdomadaire)',
				'Pratique le pardon pour libérer le “poison” intérieur',
				'Ruqya régulière pour la protection',
			],
			ar: [
				'اقرأ آية الكرسي يوميًا',
				'ارتدِ عقيقًا أحمر (كارنيليان)',
				'بخِّر بالمرّ بانتظام',
				'اغتسل بأوراق السدر أسبوعيًا',
				'تدرّب على العفو لتفريغ السمّ الداخلي',
				'رقية شرعية بانتظام للتحصين',
			],
		},
		westAfricanTraditions: {
			en: [
				"Don't eat Thiéboudienne on Tuesday nights before spiritual practice",
				'Avoid intimate relations 3 days before major spiritual work',
				"Don't cut nails on Saturday (your practice night)",
				'Never point at graves (Scorpio governs hidden realms)',
			],
			fr: [
				"Ne mange pas de Thiéboudienne le mardi soir avant une pratique",
				"Évite les relations intimes 3 jours avant un travail spirituel important",
				"Ne coupe pas les ongles le samedi (soir de pratique)",
				"Ne pointe jamais du doigt les tombes (le Scorpion régit les mondes cachés)",
			],
			ar: [
				'لا تأكل الثيبوديين يوم الثلاثاء ليلًا قبل العمل الروحي',
				'تجنّب العلاقة الزوجية 3 أيام قبل عمل روحي كبير',
				'لا تقص الأظافر يوم السبت (ليلة العمل)',
				'لا تُشر بإصبعك إلى القبور (العقرب مرتبط بعوالم الخفاء)',
			],
		},
	},
	9: {
		element: 'Fire',
		planet: 'Jupiter',
		watchOutFor: {
			en: [
				'Hip and thigh pain',
				'Liver problems',
				'Sciatic nerve pain (leg shooting pain)',
				'Accidents from overconfidence',
				'Restlessness',
			],
			fr: [
				'Douleurs des hanches et des cuisses',
				'Problèmes du foie',
				'Douleur sciatique (décharges dans la jambe)',
				'Accidents par excès de confiance',
				'Agitation',
			],
			ar: [
				'ألم في الورك والفخذ',
				'مشاكل في الكبد',
				'عرق النسا (ألم يمتد في الساق)',
				'حوادث بسبب الثقة الزائدة',
				'قلق وحركة زائدة',
			],
		},
		avoid: {
			en: [
				'Traveling without proper rest',
				'Eating too much meat',
				'Ignoring pain signals',
				'Being reckless',
				'Excess of anything',
			],
			fr: [
				'Voyager sans repos suffisant',
				'Manger trop de viande',
				'Ignorer les signaux de douleur',
				'Prendre des risques inutiles',
				"L’excès en toute chose",
			],
			ar: [
				'السفر دون راحة كافية',
				'الإكثار من اللحم',
				'تجاهل إشارات الألم',
				'التهوّر',
				'الإفراط في أي شيء',
			],
		},
		foods: {
			en: [
				'Turmeric (golden spice)',
				'Olive oil',
				'Moderate portions',
				'Foods that support the liver',
				'Stay hydrated during travel',
			],
			fr: [
				'Curcuma (épice dorée)',
				'Huile d’olive',
				'Portions modérées',
				'Aliments qui soutiennent le foie',
				'Bien s’hydrater en voyage',
			],
			ar: [
				'كركم (بهار ذهبي)',
				'زيت الزيتون',
				'كميات معتدلة',
				'أطعمة تدعم الكبد',
				'حافظ على شرب الماء أثناء السفر',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Kabīr' (O Greatest) for protection",
				'Wear Turquoise',
				'Burn Sandalwood on Thursdays',
				"Make duʿā' before traveling",
				'Practice moderation in all things',
			],
			fr: [
				"Récite « Yā Kabīr » (Ô Très-Grand) pour la protection",
				'Porte de la turquoise',
				'Brûle du santal le jeudi',
				"Fais duʿāʾ avant de voyager",
				'Pratique la modération en toute chose',
			],
			ar: [
				'ردّد «يا كبير» للتحصين',
				'ارتدِ فيروزًا',
				'بخِّر بالصندل يوم الخميس',
				'ادعُ قبل السفر',
				'الزم الاعتدال في كل شيء',
			],
		},
	},
	10: {
		element: 'Earth',
		planet: 'Saturn',
		watchOutFor: {
			en: [
				'Bone and joint pain',
				'Knee problems',
				'Feeling sad or heavy-hearted',
				'Teeth and gum issues',
				'Feeling cold all the time',
			],
			fr: [
				'Douleurs des os et des articulations',
				'Problèmes de genoux',
				'Tristesse ou lourdeur du cœur',
				'Problèmes de dents et de gencives',
				'Sensation de froid fréquent',
			],
			ar: [
				'ألم العظام والمفاصل',
				'مشاكل الركبة',
				'حزن أو ثِقَل في القلب',
				'مشاكل الأسنان واللثة',
				'الإحساس بالبرد دائمًا',
			],
		},
		avoid: {
			en: [
				'Cold and damp places',
				'Working too hard without joy',
				'Being alone for too long',
				'Eating cold or raw foods in winter',
				'Negative thinking',
			],
			fr: [
				'Lieux froids et humides',
				"Travailler trop sans moments de joie",
				'Rester seul(e) trop longtemps',
				'Manger froid ou cru en hiver',
				'Pensées négatives',
			],
			ar: [
				'الأماكن الباردة والرطبة',
				'العمل الشاق بلا راحة أو فرح',
				'العزلة الطويلة',
				'الأكل البارد أو النيء في الشتاء',
				'الأفكار السلبية',
			],
		},
		foods: {
			en: [
				'Bone broth',
				'Warming spices (ginger, cinnamon, black pepper)',
				'Warm meals',
				'Foods that build strength',
				'Hot tea throughout the day',
			],
			fr: [
				'Bouillon d’os',
				'Épices réchauffantes (gingembre, cannelle, poivre noir)',
				'Repas chauds',
				'Aliments qui renforcent',
				'Thé chaud dans la journée',
			],
			ar: [
				'مرق عظام',
				'توابل دافئة (زنجبيل، قرفة، فلفل أسود)',
				'وجبات دافئة',
				'أطعمة تقوّي الجسد',
				'شاي ساخن خلال اليوم',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Fattāḥ' (O Opener) to remove heaviness",
				'Wear Black Onyx',
				'Burn Myrrh on Saturdays',
				'Seek joy in worship',
				'Connect with community regularly',
			],
			fr: [
				"Récite « Yā Fattāḥ » (Ô Ouvreur) pour lever la lourdeur",
				'Porte un onyx noir',
				'Brûle de la myrrhe le samedi',
				'Trouve de la joie dans l’adoration',
				'Reste lié(e) à la communauté',
			],
			ar: [
				'ردّد «يا فتّاح» لرفع الثقل',
				'ارتدِ أونيكس أسود',
				'بخِّر بالمرّ يوم السبت',
				'اطلب الفرح في العبادة',
				'داوم على صلة المجتمع',
			],
		},
	},
	11: {
		element: 'Air',
		planet: 'Saturn',
		watchOutFor: {
			en: [
				'Poor blood flow in legs',
				'Ankle and calf pain',
				'Sudden cramps or spasms',
				'Nervous problems',
				'Feeling disconnected from body',
			],
			fr: [
				'Mauvaise circulation dans les jambes',
				'Douleurs des chevilles et des mollets',
				'Crampes ou spasmes soudains',
				'Troubles nerveux',
				'Sensation d’être déconnecté(e) du corps',
			],
			ar: [
				'ضعف الدورة الدموية في الساقين',
				'ألم الكاحل والربلة (بطة الساق)',
				'تشنجات مفاجئة',
				'مشاكل عصبية',
				'شعور بالانفصال عن الجسد',
			],
		},
		avoid: {
			en: [
				'Standing for long hours',
				'Tight pants or socks',
				"Electrical shocks (you're very sensitive)",
				'Isolating yourself completely',
				'Ignoring circulation problems',
			],
			fr: [
				'Rester debout de longues heures',
				'Pantalons/chaussettes serrés',
				"Chocs électriques (sensibilité élevée)",
				"S’isoler complètement",
				'Ignorer les soucis de circulation',
			],
			ar: [
				'الوقوف لساعات طويلة',
				'ملابس أو جوارب ضيقة',
				'الصدمات الكهربائية (حساسية عالية)',
				'العزلة التامة',
				'تجاهل مشاكل الدورة الدموية',
			],
		},
		foods: {
			en: [
				'Foods rich in minerals',
				'Spring water (natural, not tap)',
				'Foods that support circulation',
				'Nuts and seeds',
				'Fresh fruits',
			],
			fr: [
				'Aliments riches en minéraux',
				"Eau de source (si possible)",
				'Aliments qui soutiennent la circulation',
				'Noix et graines',
				'Fruits frais',
			],
			ar: [
				'أطعمة غنية بالمعادن',
				'ماء نبع إن تيسر',
				'أطعمة تدعم الدورة الدموية',
				'مكسرات وبذور',
				'فواكه طازجة',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Razzāq' (O Provider) for flow",
				'Wear Sapphire or Black Tourmaline',
				'Burn Frankincense on Saturdays',
				'Stay grounded through prayer',
				'Balance solitude with community',
			],
			fr: [
				"Récite « Yā Razzāq » (Ô Pourvoyeur) pour la fluidité",
				'Porte un saphir ou une tourmaline noire',
				'Brûle de l’oliban le samedi',
				'Reste ancré(e) par la prière',
				'Équilibre solitude et communauté',
			],
			ar: [
				'ردّد «يا رزّاق» لِجريان الأمور',
				'ارتدِ ياقوتًا أزرق أو تورمالين أسود',
				'بخِّر باللبان يوم السبت',
				'اثبت على الصلاة لتكون متزنًا',
				'وازن بين الخلوة وصلة الناس',
			],
		},
	},
	12: {
		element: 'Water',
		planet: 'Jupiter',
		watchOutFor: {
			en: [
				'Foot problems and infections',
				'Getting easily addicted to things',
				'Weak immunity (get sick easily)',
				'Swelling in body',
				'Mental stress showing as body sickness',
			],
			fr: [
				'Problèmes des pieds et infections',
				"Tendance aux dépendances",
				'Immunité faible (tomber malade facilement)',
				'Gonflements dans le corps',
				'Stress mental qui se manifeste physiquement',
			],
			ar: [
				'مشاكل القدم والتهابات',
				'سهولة التعلّق/الإدمان',
				'ضعف المناعة (المرض سريعًا)',
				'تورّم في الجسم',
				'ضغط نفسي يظهر كمرض جسدي',
			],
		},
		avoid: {
			en: [
				'Walking barefoot in public',
				"Any intoxicants (you're very vulnerable)",
				'Escaping problems instead of facing them',
				'Damp or moldy places',
				"Absorbing others' negative energy",
			],
			fr: [
				"Marcher pieds nus en public",
				"Toute substance intoxicante (vulnérabilité élevée)",
				"Fuir les problèmes au lieu de les affronter",
				'Lieux humides ou moisis',
				"Absorber l’énergie négative des autres",
			],
			ar: [
				'المشي حافيًا في الأماكن العامة',
				'أي مُسكِر/مُخدِّر (قابلية عالية للتأثر)',
				'الهروب من المشكلات بدل مواجهتها',
				'أماكن رطبة أو بها عفن',
				'امتصاص سلبية الآخرين',
			],
		},
		foods: {
			en: [
				'Fish',
				'Seaweed and sea vegetables',
				'Purifying herbs',
				'Foods from clean sources',
				'Strengthen immunity with good nutrition',
			],
			fr: [
				'Poisson',
				'Algues et végétaux marins',
				'Herbes purifiantes',
				'Aliments provenant de sources propres',
				'Renforcer l’immunité par une bonne alimentation',
			],
			ar: [
				'سمك',
				'أعشاب/خضار بحرية (طحالب)',
				'أعشاب للتنقية',
				'أطعمة من مصادر نظيفة',
				'تقوية المناعة بغذاء جيد',
			],
		},
		spiritualProtection: {
			en: [
				"Recite 'Yā Ḥayy' (O Ever-Living) for vitality",
				'Wear Aquamarine or Amethyst',
				'Burn Ambergris on Thursdays',
				'Protect your energy with boundaries',
				'Regular spiritual cleansing baths',
				'Keep feet clean and protected',
			],
			fr: [
				"Récite « Yā Ḥayy » (Ô Vivant) pour la vitalité",
				'Porte une aigue-marine ou une améthyste',
				'Brûle de l’ambre gris le jeudi',
				'Protège ton énergie par des limites claires',
				'Bains de purification spirituelle réguliers',
				'Garde les pieds propres et protégés',
			],
			ar: [
				'ردّد «يا حيّ» لِقوّة الحياة',
				'ارتدِ أكوامارين أو جمشت',
				'بخِّر بعنبر/عنبرgris يوم الخميس',
				'احفظ طاقتك بوضع حدود',
				'اغتسالات تنظيف روحي بانتظام',
				'احفظ قدميك نظيفتين ومحميّتين',
			],
		},
	},
};

